
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: Org2
    Domain: org2.example.com
    EnableNodeOUs: true

    Template:
      Count: 1
      SANS:
        - "192.168.1.XX"
      # Start: 5
      # Hostname: {{.Prefix}}{{.Index}} # default

    Users:
      Count: 1
